services:

  db:
    image: postgres
    restart: always 
    shm_size: 128mb
    ports:
     - "5432:5432"
    
    environment:
      POSTGRES_PASSWORD: 567234
  
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 765890
    