# Generated by Django 5.0.6 on 2024-06-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='authors',
            new_name='author',
        ),
    ]
